### ISSUE TITLE
request feature

### ISSUE THREAD

**Issue by houshym** [jpetazzo/shpod#11]
Hi
it is a useful tool but I think it will be more useful if in the container by default we can see context and ns in the command prompt. I mean kube_ps1 configured
2 having  k autocompletion  instead of kubectl
3-  all krew plugins installed it is useful too

**Comment by jpetazzo** [comment]
Hi!

I added the alias `k=kubectl` and the associated completion.

I haven't installed more krew plugins (because it's hard to choose which ones to install, and it's really fast to install them when we need them anyway) but feel free to create your own image if you'd like, of course. Normally the kube_ps1 prompt is configured already, let me know if it's not the case on your machine.

Thanks!
