### ISSUE TITLE
Support for arm64

### ISSUE THREAD

**Issue by sotiris84** [jpetazzo/shpod#3]
As the title says, could this image support arm64 architecture. I know alpine (which this image is based on) supports arm64 but I am not sure the other components if they support arm64.

Thanks

**Comment by jpetazzo** [comment]
The Dockerfile is currently hard-coded for amd64, so it'd require a bit of work to express the architecture dynamically each time. And of course, you'd have to check each component one by one to see if they provide arm64 binaries. I'll be happy to take PRs to make that happen, but I won't work on it myself since I don't have that need at the moment :)

**Comment by jpetazzo** [comment]
Check https://github.com/bretfisher/shpod, he added multi-arch support! :tada:
